apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-api
  namespace: iot-sims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-api
  template:
    metadata:
      labels:
        app: manager-api
    spec:
      serviceAccountName: sim-manager-sa
      containers:
      - name: api
        image: ghcr.io/peqspc/manager-api:latest
        imagePullPolicy: Always            
        ports:
        - containerPort: 80
        env:
        # This tells the API which simulator image to use when creating pods
        - name: SIMULATOR_IMAGE
          value: "ghcr.io/peqspc/mqtt-simulator:latest"
        - name: K8s_NAMESPACE
          value: "iot-sims"