apiVersion: v1
kind: Service
metadata:
  name: manager-api-service
  namespace: iot-sims
spec:
  type: ClusterIP
  selector:
    app: manager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # API container listens on 8000
      name: http
