apiVersion: v1
kind: Service
metadata:
  name: manager-api-service
  namespace: iot-sims
spec:
  type: ClusterIP
  selector:
    app: manager-api
  ports:
    - protocol: TCP
      port: 80        # Port inside the cluster
      targetPort: 80  # Port the container listens on