apiVersion: v1
kind: ServiceAccount
metadata:
  name: sim-manager-sa
  namespace: iot-sims
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager-role
  namespace: iot-sims
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "get", "list", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sim-manager-binding
  namespace: iot-sims
subjects:
- kind: ServiceAccount
  name: sim-manager-sa
  namespace: iot-sims
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io